Improve/update
ship-components/ship-components-highlight-click pull request #1
Opened 2017-02-28 19:30 UTC by ThinkTankShark

2017-03-14 14:53 UTC, ThinkTankShark commented
@isuttell @corescan Please let me know if you are moving forward with this component so I can fix the tests to pass, or delete the repo. Thanks

2017-03-14 15:22 UTC, isuttell submitted a review, later dismissed

2017-03-14 15:22 UTC, isuttell commented on README.md
> -[![Code Quality](https://img.shields.io/codeclimate/github/ship-components/ship-components-highlight-click.svg?style=flat)](https://codeclimate.com/github/ship-components/ship-components-highlight-cl
Why'd you remove the code quality badge?

2017-03-14 15:22 UTC, isuttell commented on tasks/config/eslint.js
> +    target: ['src/*.jsx'],
Let's leave it at the previous glob so it's grabs js files too

2017-03-23 20:16 UTC, ThinkTankShark commented on tasks/config/eslint.js
> +    target: ['src/*.jsx'],
Fixed

2017-03-23 20:24 UTC, ThinkTankShark commented on README.md
> -[![Code Quality](https://img.shields.io/codeclimate/github/ship-components/ship-components-highlight-click.svg?style=flat)](https://codeclimate.com/github/ship-components/ship-components-highlight-cl
Will add back soon.

2017-03-24 18:51 UTC, isuttell requested changes

2017-03-24 18:51 UTC, isuttell commented on tasks/config/eslint.js
> +  grunt.loadNpmTasks('grunt-eslint');
If you're using `jit-grunt`, I don't think we need to manually load the module like this. Can you verify that?

2017-03-24 18:55 UTC, ThinkTankShark commented on tasks/config/eslint.js
> +  grunt.loadNpmTasks('grunt-eslint');
It throws an error (Unknown lint Task) when testing inside the Travis env. This will fixes it.

2017-03-24 18:58 UTC, isuttell approved these changes

2017-03-24 19:33 UTC, merged